/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/init-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sms/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        phoneNumber: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        phoneNumber: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    userId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                                is_follow: number;
                                is_followed: number;
                            };
                            followingCount: number;
                            followerCount: number;
                            workCount: number;
                            likeCount: number;
                            collectCount: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/user/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        desc: string;
                        birthday: string;
                        gender: number;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: number;
                    pageSize: number;
                    type: string;
                    userId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                                is_follow: number;
                                is_followed: number;
                            }[];
                            count: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follow/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        userId: string;
                        isFollow: number;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                                is_follow: number;
                                is_followed: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remove/follower": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        userId: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                                is_follow: number;
                                is_followed: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    workId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                                is_follow: number;
                                is_followed: number;
                            };
                            work: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                title: string;
                                permission: number;
                                content: string;
                            };
                            images: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                work_id: string;
                                path: string;
                                type: number;
                            }[];
                            likeCount: number;
                            collectCount: number;
                            isLiked: number;
                            isCollected: number;
                            isOwner: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: number;
                    pageSize: number;
                    type: string;
                    targetUserId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            workList: {
                                user: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    name: string;
                                    desc: string;
                                    birthday: string;
                                    gender: number;
                                    avatar_url: string;
                                    is_complete_profile: number;
                                };
                                work: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    title: string;
                                    permission: number;
                                };
                                cover_image: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    work_id: string;
                                    path: string;
                                    type: number;
                                };
                                likeCount: number;
                                isLiked: number;
                                isOwner: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        workId: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/work/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: number;
                    pageSize: number;
                    type: string;
                    workId: string;
                    rootCommentId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            comments: {
                                user: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    name: string;
                                    desc: string;
                                    birthday: string;
                                    gender: number;
                                    avatar_url: string;
                                    is_complete_profile: number;
                                };
                                comment: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    content: string;
                                    work_id: string;
                                    user_id: string;
                                    parent_id: string;
                                    root_comment_id: string;
                                };
                                isLiked: number;
                                likeCount: number;
                                replyCount: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create/work/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                        workId: string;
                        rootCommentId: string;
                        parentId: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                            };
                            comment: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                content: string;
                                work_id: string;
                                user_id: string;
                                parent_id: string;
                                root_comment_id: string;
                            };
                            isLiked: number;
                            likeCount: number;
                            replyCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/create/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        userId: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                type: number;
                            };
                            sessionMember: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                session_id: string;
                                user_id: string;
                                last_read_seq: number;
                                is_pin: number;
                                other_user_id: string;
                            };
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                            };
                            latestMessage: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                type: number;
                                payload: {
                                    1?: Record<string, never>;
                                    2?: {
                                        report_id: string;
                                    };
                                    3?: {
                                        work_id: string;
                                        title: string;
                                        cover_url: string;
                                    };
                                };
                                session_id: string;
                                user_id: string;
                                content: string;
                                inc_seq: number;
                            };
                            unreadCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/get/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: number;
                    pageSize: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessions: {
                                session: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    type: number;
                                };
                                sessionMember: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    session_id: string;
                                    user_id: string;
                                    last_read_seq: number;
                                    is_pin: number;
                                    other_user_id: string;
                                };
                                user: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    name: string;
                                    desc: string;
                                    birthday: string;
                                    gender: number;
                                    avatar_url: string;
                                    is_complete_profile: number;
                                };
                                latestMessage: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    type: number;
                                    payload: {
                                        1?: Record<string, never>;
                                        2?: {
                                            report_id: string;
                                        };
                                        3?: {
                                            work_id: string;
                                            title: string;
                                            cover_url: string;
                                        };
                                    };
                                    session_id: string;
                                    user_id: string;
                                    content: string;
                                    inc_seq: number;
                                };
                                unreadCount: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/pin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        sessionMemberId: string;
                        isPin: number;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/send/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        sessionId: string;
                        content: string;
                        type: number;
                        payload: {
                            1?: Record<string, never>;
                            2?: {
                                report_id: string;
                            };
                            3?: {
                                work_id: string;
                                title: string;
                                cover_url: string;
                            };
                        };
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                type: number;
                                payload: {
                                    1?: Record<string, never>;
                                    2?: {
                                        report_id: string;
                                    };
                                    3?: {
                                        work_id: string;
                                        title: string;
                                        cover_url: string;
                                    };
                                };
                                session_id: string;
                                user_id: string;
                                content: string;
                                inc_seq: number;
                            };
                            user: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                name: string;
                                desc: string;
                                birthday: string;
                                gender: number;
                                avatar_url: string;
                                is_complete_profile: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/get/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: number;
                    pageSize: number;
                    sessionId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            messages: {
                                message: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    type: number;
                                    payload: {
                                        1?: Record<string, never>;
                                        2?: {
                                            report_id: string;
                                        };
                                        3?: {
                                            work_id: string;
                                            title: string;
                                            cover_url: string;
                                        };
                                    };
                                    session_id: string;
                                    user_id: string;
                                    content: string;
                                    inc_seq: number;
                                };
                                user: {
                                    id: string;
                                    created_at: string;
                                    updated_at: string;
                                    name: string;
                                    desc: string;
                                    birthday: string;
                                    gender: number;
                                    avatar_url: string;
                                    is_complete_profile: number;
                                };
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    reportId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            report: {
                                id: string;
                                created_at: string;
                                updated_at: string;
                                work_id: string;
                                reporter_id: string;
                                report_object: number;
                                report_type: number;
                                reason: string;
                                status: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        workId: string;
                        reportType: number;
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            types: {
                                text: string;
                                id: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        employee_id: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/add/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 请求体参数 */
            requestBody: {
                content: {
                    "application/json": {
                        employee_id: string;
                        role: number;
                        name: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 响应模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        heartbeatClientEvent: {
            jwt: string;
        };
        errorClientEvent: {
            msg: string;
        };
        pushChatMessageEvent: {
            message: {
                id: string;
                created_at: string;
                updated_at: string;
                type: number;
                payload: {
                    1?: Record<string, never>;
                    2?: {
                        report_id: string;
                    };
                    3?: {
                        work_id: string;
                        title: string;
                        cover_url: string;
                    };
                };
                session_id: string;
                user_id: string;
                content: string;
                inc_seq: number;
            };
            user: {
                id: string;
                created_at: string;
                updated_at: string;
                name: string;
                desc: string;
                birthday: string;
                gender: number;
                avatar_url: string;
                is_complete_profile: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
