# 开发环境docker-compose配置

version: '3'

networks:
  dev:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: ../frontend/build/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/dev.conf:/etc/nginx/nginx.conf
      - /var/opt/xiaochengshu/upload:/var/opt/upload
      - /var/opt/xiaochengshu/frontend/logs:/var/log/nginx
    networks:
      - dev

  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:9.0.0
    container_name: mysql
    env_file:
      - ./mysql/.env
    volumes:
      - /var/opt/xiaochengshu/mysql/log:/var/log/mysql
      - /var/opt/xiaochengshu/mysql/data:/var/lib/mysql
      - /etc/opt/xiaochengshu/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      - dev

  # 启动前需要按照config/back.env.temp模板创建.env文件
  # 并通过volume挂载到容器中
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../backend/build/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ../backend:/opt/xiaochengshu # 开发环境挂载代码目录热更新
      - /var/opt/xiaochengshu/upload:/var/opt/upload # 挂载静态文件目录,和frontend容器共享,用于存储静态资源
    env_file:
      - ./backend/.env
    networks:
      - dev