# 开发环境nginx配置文件
worker_processes  1;
events {
    worker_connections  1024;
}

http {
    include       mime.types;
    gzip  on;
    sendfile  on;

    server {
        listen       80;
        server_name  localhost;
        charset utf-8;

        client_max_body_size 100M;

        location ^~ /upload {
            alias /var/opt/upload;
        }

        location /api/connect {
            proxy_pass http://backend:8080;
            proxy_http_version 1.1;
            proxy_set_header Connection '';
            proxy_buffering off;
            proxy_cache off;
            chunked_transfer_encoding on;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location ^~ /api {
            proxy_pass http://backend:8080;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }
}