name: xiaochengshu-actions

on: 
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  copy:
    runs-on: ubuntu-22.04
    steps:
      - name: pull repository code
        uses: actions/checkout@v4
      - name: print
        run: |
          echo "当前所在目录"
          pwd
          echo "目录文件"
          ll














    
