name: xiaochengshu-actions

on: 
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  copy:
    runs-on: ubuntu-22.04

    # 拉取代码
    steps:
      - name: Pull repository code
        uses: actions/checkout@v4

      # 替换相关配置文件
      - name: Replace secret
        env:
          BACKEND_DB_DATABASE: ${{ secrets.BACKEND_DB_DATABASE }}
          BACKEND_DB_HOST: ${{ secrets.BACKEND_DB_HOST }}
          BACKEND_DB_PASSWORD: ${{ secrets.BACKEND_DB_PASSWORD }}
          BACKEND_DB_PORT: ${{ secrets.BACKEND_DB_PORT }}
          BACKEND_DB_USER: ${{ secrets.BACKEND_DB_USER }}
          BACKEND_ENV: ${{ secrets.BACKEND_ENV }}
          BACKEND_JWT_SECRET: ${{ secrets.BACKEND_JWT_SECRET }}
          BACKEND_PERSISTENT_HEARTBEAT_INTERVAL: ${{ secrets.BACKEND_PERSISTENT_HEARTBEAT_INTERVAL }}
          BACKEND_UPLOAD_DIR: ${{ secrets.BACKEND_UPLOAD_DIR }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_SSH_PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD }}
          SERVER_SSH_USERNAME: ${{ secrets.SERVER_SSH_USERNAME }}
        run:
          chmod 733 ./deploy/replace_secret.sh
          ./deploy/replace_secret.sh

      # 拷贝项目到服务器
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 22
          source: "."
          target: /opt/xiaochengshu/
      
      # 通过ssh连接到部署
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 22
          script: /opt/xiaochengshu/deploy/deploy.sh
